package com.deendayalproject.model.request

data class InsertLivingAreaReq(
    val loginId: String,
    val appVersion: String,
    val imeiNo: String,
    val trainingCentre: Int,
    val sanctionOrder: String,
    val facilityId: Int,
    val roofType: String,
    val falseCeiling: String,
    val ceilingHeight: String,
    val length: String,
    val width: String,
    val area: String,
    val windowArea: String,
    val airConditioning: String,
    val cot: String,
    val mattress: String,
    val bedSheet: String,
    val storage: String,
    val infoBoard: String,
    val studentsPermitted: String,
    val lights: String,
    val fans: String,
    val typeOfRoofFilePath: String,
    val falseCeilingFilePath: String,
    val ceilingHeightFilePath: String,
    val areaFilePath: String,
    val windowAreaFilePath: String,
    val airConditioningFilePath: String,
    val cotFilePath: String,
    val mattressFilePath: String,
    val bedSheetFilePath: String,
    val storageFilePath: String,
    val infoBoardFilePath: String,
    val lightsFilePath: String,
    val fansFilePath: String
)

